# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
 vmImage: 'windows-2019'

# do this before all your .NET Core tasks
steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.301' # replace this value with the version that you need for your project
# ...

steps:
- script: dotnet restore

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: 'WebAPI_MongoDB.csproj'
    arguments: '--configuration Release' # Update this to match your need
